# Site settings
title: Damiano Braga
email: damiano.braga@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Damiano Braga - Sr. Software Engineer at Trulia - Personal Page , Projects and Blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dbraga.io" # the base hostname & protocol for your site
twitter_username: DamiTweet
github_username:  dbraga
linkedin_url : http://www.linkedin.com/pub/damiano-braga/38/736/998
stackoverflow_url: http://stackoverflow.com/users/1606382/dbraga

# Build settings
markdown: kramdown
